export const mockUsers = [
    {
        avatar: '11',
        name: 'Иван',
        message: 'привет',
        time: '11:46',
        bage: '1',
    },
    {
        avatar: '11',
        name: 'Галина',
        message: 'привет',
        time: '11:46',
        bage: '1',
    },
    {
        avatar: '12',
        name: 'Андрей',
        message: 'Изображение',
        time: '10:49',
        bage: '2',
    },
    {
        avatar: '13',
        name: 'Мария',
        message: 'Сейчас перезвоню',
        time: '09:30',
        bage: '3',
    },
    {
        avatar: '14',
        name: 'Олег',
        message: '👍',
        time: '08:15',
        bage: '4',
    },
    {
        avatar: '15',
        name: 'Светлана',
        message: 'Спасибо!',
        time: '08:15',
        bage: '1',
    },
    {
        avatar: '13',
        name: 'Мария',
        message: 'Сейчас перезвоню',
        time: '09:30',
        bage: '3',
    },
    {
        avatar: '14',
        name: 'Олег',
        message: '👍',
        time: '08:15',
        bage: '4',
    },
    {
        avatar: '15',
        name: 'Светлана',
        message: 'Спасибо!',
        time: '08:15',
        bage: '1',
    },
    {
        avatar: '13',
        name: 'Мария',
        message: 'Сейчас перезвоню',
        time: '09:30',
        bage: '3',
    },
    {
        avatar: '14',
        name: 'Олег',
        message: '👍',
        time: '08:15',
        bage: '4',
    },
    {
        avatar: '15',
        name: 'Светлана',
        message: 'Спасибо!',
        time: '08:15',
        bage: '1',
    },
    {
        avatar: '14',
        name: 'Олег',
        message: '👍',
        time: '08:15',
        bage: '4',
    },
    {
        avatar: '15',
        name: 'Светлана',
        message: 'Спасибо!',
        time: '08:15',
        bage: '1',
    },
];
export const mockProfile = [
    { description: 'Почта', data: 'pochta@yandex.ru' },
    { description: 'Логин', data: 'ivanivanov' },
    { description: 'Имя', data: 'Иван' },
    { description: 'Фамилия', data: 'Иванов' },
    { description: 'Имя в чате', data: 'Иван' },
    { description: 'Телефон', data: '8 (888) 123-45-55' },
];
